project:
  type: website
  output-dir: _site

website:
  title: "My Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    self-contained: true
    theme: cosmo