project:
  title: "lab 6"
  output-dir: docs
  type: website

website:
  title: "lab6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    self-contained: true
    theme: cosmo